# Cache CSS files for 1 month
[[headers]]
for = "/**/*.css"
[headers.values]
Cache-Control = "public, max-age=2592000"

# Cache JS files for 1 month
[[headers]]
for = "/**/*.js"
[headers.values]
Cache-Control = "public, max-age=2592000"

# Cache image files for 1 month
[[headers]]
for = "/**/*.{png,jpg,jpeg,gif,svg,webp,avif,ico}"
[headers.values]
Cache-Control = "public, max-age=2592000"