baseURL = 'https://jayakrishnancn.netlify.app/'
languageCode = 'en-us'
title = 'Jayakrishnan C N'
theme = "base-blog-theme"

summaryLength = 15

[[menus.main]]
name = 'About'
pageRef = '/'
weight = 1


[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 2


[[menus.main]]
name = 'Blog Posts'
pageRef = '/posts'
weight = 3

[[menus.main]]
name = 'LinkedIn'
url = 'https://www.linkedin.com/in/jayakrishnancn/'
weight = 4
params.new_tab = true

[[menus.main]]
name = 'GitHub'
url = 'https://github.com/jayakrishnancn/'
weight = 5
params.new_tab = true

[markup]
[minify]
minifyOutput = true
